#!/usr/bin/env bash

# Installation script "borrowed" from Borkdude's babashka installation script.
# Consider checking out and/or supporting Borkdude's excellent work and cool projects: https://raw.githubusercontent.com/borkdude/

set -euo pipefail


default_install_dir="/usr/local/bin"
install_dir=$default_install_dir
download_dir=/tmp
latest_release="$(curl -sL https://raw.githubusercontent.com/theiceshelf/firn/master/clojure/resources/FIRN_VERSION)"

case "$(uname -s)" in
    Linux*)     platform=linux;;
    Darwin*)    platform=mac;;
esac

download_url="https://github.com/theiceshelf/firn/releases/download/v$latest_release/firn-$platform.zip"

cd "$download_dir"
echo -e "Downloading Firn from: $download_url."
curl -o "firn-$latest_release-$platform.zip" -sL $download_url
unzip -qqo "firn-$latest_release-$platform.zip"
chmod +x firn
rm "firn-$latest_release-$platform.zip"
mv firn /usr/local/bin
echo "Installed Firn to usr/local/bin"
