
🚧 Static site generator using org-mode. Under Development. Not recommended for use.

* What's this?

Firn generates a website from your .org mode files. It's original intention was
to support the building of a flat file wiki, but it can handle nested folders.

Currently, running the program on a directory of org files performs the following:

- Reads all .org files in the directory recursively.
- Load up layouts and partials and read these templates from hiccup files.
- Iterates over files and runs them through [[https://github.com/PoiScript/orgize][Orgize]], then turns the resulting
  data into html.
  
* Usage

No out-of-the-box usage yet. You're going to need emacs, a repl and some coffee.

* Assumptions / Limitations

- the content _directory name_ (ex: "my_wiki") should not exist anywhere else in
  the path to a file in the wiki.
  - for example, this is bad: =/development/my_wiki/some_more_dirs/my_wiki/file_1.org=
  - Unlikely that user's will have this, but it's currently a limitation nonetheless.
- Org mode links should be set to relative. You can probably do this with
  dir-locals and setting [[https://emacs.stackexchange.com/questions/32601/how-can-i-get-with-org-store-link-relative-path-instead-of-absolute][org-link-file-path-type]] to =relative=. Read [[file:docs/setup.org][setup]] for
  more details.

* Developing

Versions:

- Clojure / Lein - 1.9.0
- rustc 1.41.1

Up and atom ⚛ :zap::

#+BEGIN_SRC sh
git clone git@github.com:theiceshelf/firn.git
cd firn
lein deps
cargo build
#+END_SRC

Then boot up your ol' trusty and run cider-jack-in on =firn.core-test= to tamper
with the built in sample org wiki (=test/firn/demo_org/=)
