#+TITLE: Backlinks and Related Files
#+FIRN_UNDER: Content "The Render Function"
#+FIRN_ORDER: 4
#+DATE_UPDATED: <2020-10-21 13:47>
#+DATE_CREATED: <2020-09-20 Sun 19:05>


*Purpose:* This document explains how to render a list of *backlinks*  or *related files* in your Firn layouts.

*Prerequistes*: an understanding of [[file:the-render-function.org][The Render Function]] and how [[file:layout.org][layouts]] work.

* Overview

/Backlinks/ are used to display a list of links to the /current/ document you are
reading. A document has backlinks if an org-mode file links to another org-mode file
using a "[[https://orgmode.org/manual/External-Links.html][file]]" link.

/Related Files/ are files that /might/ be related because they share a tag with the
file being rendered.

Generally, these render functions make exploring a large wiki-type site more
easily navigatable. These render functions were largely inspired by [[https://github.com/org-roam/org-roam][org-roam]],
which Firn tries to integrate with on a basic level (see: [[file:firn_tags.org][firn tags]]).

* Usage

#+BEGIN_SRC clojure
(render :backlinks)
;; output =>
[:ul.firn-backlinks
 [:li.firn-backlink
  [:a {:href "/file1"} "Org Mode"]]]

(render :related-files)
;; output =>
[:ul.firn-related-files
 [:li.firn-related-file
  [:a.firn-related-file-link {:href "/file-small"} "Firn"]]]
#+END_SRC

The above will render a list of backlinks and related-files. If a file has
neither backlinks or related files these functions will return ~nil~.
