#+TITLE: Changelog
#+FIRN_ORDER: 5
#+FIRN_TOC: {:depth 1}
#+FIRN_UNDER: Reference

* V.0.0.9

** New
- Add ~(render :sitemap)~ (with options for :sort-by, :start-at )
- Add ~(render :breadcrumbs)~ breadcrumbs
- [ ] previous-file
- [ ] next-file
- [ ] siblings
** Fixed
** Breaking Changes

* V.0.0.8
** Feature: Clean up unused attachments.
- Adds a configuration option to config.edn: ~run-build-clean?~ - which will
  remove unused file attachments from ~_firn/_site~ after finishing building.
  - if "always" -> always remove unusued attachments from final _site output.
  - if "prompt" -> CLI will prompt user to delete files.
  - if "never" -> CLI will never delete unusued attachments.

** Feature: Exclude files from site-map.
- User's can exclude org files from showing in the site-map by using the ~#+FIRN_SITEMAP?~ in-buffer-setting.
** Refactor: site-link ([[https://github.com/theiceshelf/firn/pull/33][33]])
- Enables Firn sites to be hosted at non-root addresses.
- Before, all internal href links were relative. Now they are absolute and based off the ~:site-url~ value in a user's ~config.edn~
** Feature: Folding ([[https://github.com/theiceshelf/firn/pull/34][34]])
- headlines and their content can be folded on a site-wide, layout-wide, or file-specific basis.
** Breaking Changes
- when rendering a table of contents, the options map has renamed a key from "exclusive?" to "exclude-headline?". As such:

#+BEGIN_SRC clojure
(render :toc {:headline "Headings" :depth 1 :exclude-headline? true}) ; is now valid
(render :toc {:headline "Headings" :depth 1 :exclusive? true}) ; no longer works.
#+END_SRC

* V.0.0.7
** Feature: Pages
- user's can create "Pages" now.
- Creating a [[file:pages.org][page]] in ~_firn/pages/my_page.clj~ will similar to layouts, convert hiccup to html.
** Feature: Tags and Tag Page
- tags are now displaying in headlines.
- tags in headlines are links to a /tags page, anchored to the respective tag clicked.
- The "tags.clj" page is created out of the box with a new Firn site.
- The tags page lists all tags across all headlines in all files; each a link that jumps to the respective heading.
