#+TITLE: Configuration
#+FIRN_ORDER: 1

* Overview

Like many other static site generators, Firn can be configured. Configuration happens in the =config.edn= file at the root of the Firn site that is generated when you run =firn new= from the command line.

When you build or serve your site using the Firn CLI, this file is read into memory and its values are made available to the functions that compile your site. You can inspect the configuration API of this file at the [[config.edn][bottom of this document.]]

* Overriding configuration

Any property that begins with =:firn-*= is a field that will /impact the rendering of your files/. Specifically, these values correspond to what are known as [[https://orgmode.org/manual/In_002dbuffer-Settings.html][in-buffer settings]] in org-mode. Any of these fields in your configuration can be overridden in a single file's in-buffer settings. For example, in your config, you might turn off property rendering:

#+BEGIN_SRC clojure
{;...
 :firn-properties? false
 ;...
 }
#+END_SRC

This ensures that no property-drawers are rendered under their respective headlines. However, you may have a single file that you want to render the property drawers for, when relevant. At the top of the file in question, you would override this setting by adding this in-buffer setting:

#+BEGIN_SRC
#+FIRN_PROPERTIES?: true
#+END_SRC

*NOTE:* in-buffer settings for Firn must be at the top of the file, must be in all capitals, use underscores where hyphens are used in your config, and the values must properly map to a Clojure value. The following in-buffer settings are incorrect:

#+BEGIN_SRC clojure
#+FIRN-PROPERTIES?: true ; should use an underscore

#+FIRN_PROPERTIES?: True ; "True" is not a valid clojure value

#+FIRN_PROPERTIES?: t    ; "t" is not a valid clojure value

#+firn_properties?: t    ; "t" is not valid, and firn_properties? should be upper cased.
#+END_SRC

* Usage

Most values in =config.edn= are simple, scalar values - integers, strings, etc. For the sake of clarity, this section will go over settings that have compound values and the usage of which are not immediately clear.

** Table of Contents

The firn table of contents is rendered in a layout. If you use the default layout in Firn, it will be at the top of the file. See [[file:layout.org][layouts]] for more information. =:firn-toc= is configured as a map with possible values of =depth=, =headline=, and =exclusive?=

#+BEGIN_SRC clojure
{:depth 3          ; render only headlines that are of level 3 and below in the table of contents.
 :headline "Notes" ; The table of contents will begin at the headline "Notes"
 :exclude-headline? true  ; Do not render the headline "Notes", just its children.
}
#+END_SRC
* Reference                                                      :reference:
** config.edn

| Key               | Type    | Purpose                                                |
|-------------------+---------+--------------------------------------------------------|
| =:dir-data=         | string  | org-attachments/files to get copied into _site.        |
| =:enable-rss?=      | boolean | If true, creates a feed.xml in _site.                  |
| =:firn-properties?= | boolean | Files: whether to render properties under all headings |
| =:firn-toc=         | map     | Files: settings for any rendered table of contents.    |
| =:ignored-dirs=     | vector  | Dirs of org files to ignore at build time.             |
| =:site-desc=        | string  | The description of your site, used for RSS.            |
| =:site-title=       | string  | The title of your site, used for RSS.                  |
| =:site-url=         | string  | The root url of your site.                             |
| =:site-map-pages?=  | boolean | Whether to include custom pages in your site-map       |

** Per-file configuration

The following in-buffer settings are processed by Firn and/or made available to layouts for processing.

| Key                | Type          | Purpose                                         |
|--------------------+---------------+-------------------------------------------------|
| ~#+TITLE:~           | string        | Used in site-map, links, etc                    |
| ~#+DATE_CREATED~     | org-mode-date | File date created                               |
| ~#+DATE_UPDATED~     | org-mode-date | File last updated                               |
| ~#+FIRN_PROPERTIES?~ | boolean       | Whether to render properties under all headings |
| ~#+FIRN_TOC~         | map           | Settings for any rendered table of contents     |
| ~#+FIRN_ORDER~       | integer       | Enables sorting files in the site-map           |
| ~#+FIRN_PRIVATE~     | boolean       | Whether or not to read the file in question     |
| #+FIRN_SITEMAP?    | boolean       | Whether to include the file in the site-map.    |
| ~#+FIRN_UNDER~       | string        | Category for which the documents falls under    |
