#+TITLE: Limitations
#+DATE_CREATED: <2020-03-27 Fri>
#+DATE_UPDATED: <2020-09-23 18:47>
#+FIRN_UNDER: Reference
#+FIRN_ORDER: 3

* Development Server

- The file watcher (reloading of files on change) is a bit slow.
- Certain site-wide data/metadata collected happens at the initial compile time. Things like the site-logs, site-map, site-links *do not* get updated when a single file is updated when using the development server. You will need to re-start the server to re-process the files.

* Attachments                                                    :attachments:

- Currently, Firn copies the _entirety of this folder into your build output_.
  This means that if you have attachments which are private or simply unlinked
  to from org-files, they will be included in your build output. You can enable
  the "cleaning" (removal) of unused attachments by enabling the
  ~:run-build-clean?~ flag in your [[file:configuration.org][config.edn file]].
- Org-attach links are not supported.

* Footnotes

This does not affect user's who are using the Firn binary - only those using the
repl within the repo.

Currently it seems that *in dev-mode* - ie. when in the repl and using the
pre-compiled rust parser, footnotes definitions that have children on the same
line are not parse-able:

=[fn:1] Content here < fails the parser.=

Whereas, if you add a newline and add the content below, it works.
So, far this seems to be fine using the final compiled Firn binary.
* Inline HTML

If you have any html elements in your org-file, they will be rendered as html - this is not necessarily a limitation, but as of now, it is not possible to "escape" html, such as in inline code blocks.
