#+TITLE: Logbooks
#+FIRN_UNDER: Content "The Render Function"
#+FIRN_FOLD: {2 true 3 true}
#+FIRN_ORDER: 8
#+DATE_UPDATED: <2020-09-25 19:07>
#+DATE_CREATED: <2020-09-22 Tue 17:10>

*Purpose:* An overview of rendering time-based data.

*Prerequistes*: an understanding of [[file:the-render-function.org][The Render Function]] and [[file:layout.org][layouts]].

*Note*: Logbook support is rudimentary and in-progress of being built.

* Overview

When parsing your org-mode files, Firn collects Logbook data in the case that
you want to render time-based visuals.

* Usage
** Rendering Logbook Visualizations

Currently, there is limited experimentation with rendering SVG charts based on logbook data. It is likely that this render option *will be deprecated* as a better alternative is developed.

Come back soon!

*** Logbook Polyline

Graphs all logbook entries for the current file in a polyline, generating a chart for each year.

#+BEGIN_SRC clojure
(defn default
  [{:keys [render partials]}]
  (let [{:keys [head]} partials]
    (head)
    [:body
      [:div (render :logbook-polyline {:stroke "#45698A" :height 60 :width 365})]]))
#+END_SRC

** Accessing raw logbook data

Logbook data is available in your layouts.

- ~site-logs~ provides log data for *all* logbooks across all files.
- ~logbook~ provides data for *the* file you are rendering.

#+BEGIN_SRC clojure
(defn default
  [{:keys [logbook site-logs]}]
  [:html
   [:body
   ; ...
    ]]

#+END_SRC

Both the ~logbook~ and ~site-logs~ are lists of maps that look roughly like so:

#+BEGIN_SRC clojure
[{:end-ts 1600792920000,
  :start {:year 2020, :month 9, :day 20, :dayname "Sun", :hour 16, :minute 42},
  :start-ts 1600620120000,
  :type "clock",
  :duration "48:00",
  :from-headline "Overview",
  :post_blank 0,
  :end {:year 2020, :month 9, :day 22, :dayname "Tue", :hour 16, :minute 42},
  :from-url "http://localhost:4000/folding",
  :file-tags nil,
  :from-file "Folding"}]
#+END_SRC
