#+TITLE: Custom Pages
#+DATE_CREATED: <2020-03-24 Tue>
#+DATE_UPDATED: <2020-08-14 14:03>
#+FIRN_LAYOUT: docs
#+FIRN_UNDER: ["Content"]
#+FIRN_ORDER: 4

* Overview

Similar to [[file:layout.org][layouts]], on creating a Firn site, you will find a folder: =_firn/pages=. This folder enables users to create custom pages that are converted from the template language (hiccup) into HTML. This is useful if you want to create a page that does not render any org-mode content.

* Tags - an out of the box page                                 

Creating a new firn site comes with a custom page: =tags.clj=. This file exists to provide an example of a custom page, as well as to give user's an out-of-the-box solution for rendering tags with Firn. When Firn processes your org-mode files, it collects all heading tags, and stores them in a Clojure vector (simply, a list). This list of tags are made available to layouts and pages - in this case, the latter, which uses it to render all the tags your org-mode content has. You can of course delete this file if you do not want to render tags.

* Differences from layouts

Pages have less data available to them at site-generation time. Because there are no org-mode files concerned, there is no =render= function. The following content is available to a page, which like layouts, can be destructured and made available to your Clojure hiccup function.

| Function/Data | Intent                                     | Data-type          |
|---------------+--------------------------------------------+--------------------|
| config        | The site wide config                       | map                |
| partials      | a list of invokable partials =/partials= dir | list               |
| site-links    | A list of all links across all documents   | vector             |
| site-logs     | A list of all logbook entries              | vector             |
| site-map      | A list of all files on a site              | vector             |
| site-tags     | A list of all tags across all org files    | map (string<>list) |

* Limitations

** Metadata
Custom pages will not sort in the site-map. Site-map metadata, such as the =firn-order=, or =firn-under= values enable to sort and group your site-map as you like. This data is gathered from org-mode keywords. Because custom pages in the =/pages= directory do not have this metadata available, they are rendered with a pre-configured set of metadata as so:

#+BEGIN_SRC clojure
{:path       "/<the-file-name>" ; the file path must have no spaces, and will become the web path
 :title      "The file name"    ; the file path is converted into a sentence cased value
 :firn-order 9999               ; pages will auto group at at the end of the site-map
 :firn-under "Page"})))         ; pages are grouped under "Pages"
#+END_SRC
** Flat routing

Currently, Firn only supports creating custom pages at the root level of =/pages= - unlike org-mode files, if you have a directory within the =/pages= directory, it will not translate to a nested url. For example, if you have the file =/pages/my-category/my-custom-page-1.clj= - it will be translated into an html file named =my-custom-page-1.html= at the root of your site url.
