#+TITLE: Firn Setup
#+DATE_CREATED: <2020-03-27 Fri>
#+DATE_UPDATED: <2020-05-10 15:16>
#+FILE_UNDER: docs
#+FIRN_LAYOUT: docs

The following are notes on how to best setup your editor and folder for a Firn
site.

* Folder Structure

Firn was originally intended to build sites from a flat wiki structure but this
is not mandatory. This works well with [[https://github.com/jethrokuan/org-roam][Org-Roam]], which I use in this setup
currently. Not required, but useful. You can have nested folders, which /will/
translate into nested url paths.

An example directory:

#+BEGIN_SRC
❯ tree -L 2
.
├── _firn
│   ├── _site
│   ├── bin
│   ├── layouts
│   ├── partials
│   └── static
├── attach
│   ├── _20200328_190456_an_attachment.jpg
│   └── test-img.png
├── file1.org        # => site.com/file1.html
├── file2.org        # => site.com/file2.html
└── foo
    └── level-2.org  # => site.com/foo/file1.html

#+END_SRC
* Links
** Linking between files

All links should be relative.

In your wiki directory, add a =.dir-locals.el= file with these contents to make
sure org links are relative (or just change it in your config.el if you don't
mind having this setting apply across all org files.):

#+BEGIN_SRC elisp
((org-mode
  (org-link-file-path-type . relative)))
#+END_SRC

** Attachments

When it comes to attachments:

- It's recommended to put all images/attachments in a single folder (your
  =:dir-data=)
- You can configure which directory this is via the =:dir-data= key in your
  config.

* Other Things
** How To get auto timestamp on =DATE_UPDATED= on every file in emacs.

- Ensure that you have a =#+DATE_UPDATED= keyword in your org-files:

#+BEGIN_SRC org
#+TITLE: Firn
#+DATE_CREATED: <2020-03-01 09:53>
#+DATE_UPDATED: <2020-03-22 13:24>
#+END_SRC

- In your wiki directory, add a =.dir-locals= file with these contents

#+BEGIN_SRC elisp
((org-mode
  (time-stamp-pattern . "8/DATE_UPDATED:[ 	]+\\\\?[\"<]+%:y-%02m-%02d %02H:%02M\\\\?[\">]")
  ))
#+END_SRC

- Somewhere in your config, add a hook to run emacs' time-stamp function on save:

#+BEGIN_SRC elisp
(add-hook 'write-file-hooks 'time-stamp) ; update timestamp, if it exists, when saving
#+END_SRC
** Ignoring certain files or directories.

Setting the keyword ~#+FIRN_PRIVATE: true~ in an org-mode file will cause the file
not to be rendered. Similarly, you can set an entire directory to be ignored in
your =config.edn=
