#+TITLE: Static Assets / Attachments
#+FIRN_UNDER: Content
#+FIRN_ORDER: 50

This document discusses how to include static front-end assets (css, js, images) and org-mode attachments in your Firn site.

* Static Assets

Running ~firn new~ scaffolds a firn site, including the creation of a folder named ~static~:

#+BEGIN_SRC
static
├── css
│   ├── firn_base.css # firn_base is included when a firn site is created
├── img
│   └── favicon.png
└── js
    └── main.js
#+END_SRC

These files will be transferred over to your built site when you run ~firn build~.

The static directory is where you want to put all your CSS, JavaScript, and site-wide images (such as a favicon).

* Org attachments

Firn does not support org-attach, but does support including [[https://orgmode.org/manual/External-Links.html][file link]]
attachments. If you want images in your org-files to appear as in your built
side, you need to centralize your images in a single folder. By default, a new
Firn site looks for aa directory called ~data~, and then assumes that you are
linking images into your documents from any subsequent folder under ~data~.
